version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-secrets-management-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2ex2qipt7h5t"
s3_prefix = "sam-secrets-management-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
